package bridge

// Error messages from kalkancrypt
const (
	KCR_BASE                  = 0x08F00000
	KCR_OK                    = 0x00000000
	KCR_INIT_ERROR            = KCR_BASE + 0x00000001
	KCR_ERROR_READ_PKCS12     = KCR_BASE + 0x00000002
	KCR_ERROR_OPEN_PKCS12     = KCR_BASE + 0x00000003
	KCR_INVALID_PROPID        = KCR_BASE + 0x00000004
	KCR_BUFFER_TOO_SMALL      = KCR_BASE + 0x00000005
	KCR_CERT_PARSE_ERROR      = KCR_BASE + 0x00000006
	KCR_INVALID_FLAG          = KCR_BASE + 0x00000007
	KCR_OPENFILEERR           = KCR_BASE + 0x00000008
	KCR_INVALIDPASSWORD       = KCR_BASE + 0x00000009
	KCR_CERTWRONGDATE         = KCR_BASE + 0x0000000a
	KCR_CERTEXPIRED           = KCR_BASE + 0x0000000b
	KCR_ISNOTCACERT           = KCR_BASE + 0x0000000c
	KCR_MEMORY_ERROR          = KCR_BASE + 0x0000000d
	KCR_CHECKCHAINERROR       = KCR_BASE + 0x0000000e
	KCR_CACERTKEYUSAGEERROR   = KCR_BASE + 0x0000000f
	KCR_VALIDTYPEERROR        = KCR_BASE + 0x00000010
	KCR_BADCRLFORMAT          = KCR_BASE + 0x00000011
	KCR_LOADCRLERROR          = KCR_BASE + 0x00000012
	KCR_LOADCRLSERROR         = KCR_BASE + 0x00000013
	KCR_UNKNOWN_ALG           = KCR_BASE + 0x00000015
	KCR_KEYNOTFOUND           = KCR_BASE + 0x00000016
	KCR_SIGN_INIT_ERROR       = KCR_BASE + 0x00000017
	KCR_SIGN_ERROR            = KCR_BASE + 0x00000018
	KCR_ENCODE_ERROR          = KCR_BASE + 0x00000019
	KCR_INVALID_FLAGS         = KCR_BASE + 0x0000001a
	KCR_CERTNOTFOUND          = KCR_BASE + 0x0000001b
	KCR_VERIFYSIGNERROR       = KCR_BASE + 0x0000001c
	KCR_BASE64_DECODE_ERROR   = KCR_BASE + 0x0000001d
	KCR_UNKNOWN_CMS_FORMAT    = KCR_BASE + 0x0000001e
	KCR_GETHASHERROR          = KCR_BASE + 0x0000001f
	KCR_CA_CERT_NOT_FOUND     = KCR_BASE + 0x00000020
	KCR_XMLSECINIT_ERROR      = KCR_BASE + 0x00000021
	KCR_LOADTRUSTEDCERTSERR   = KCR_BASE + 0x00000022
	KCR_SIGN_INVALID          = KCR_BASE + 0x00000023
	KCR_NOSIGNFOUND           = KCR_BASE + 0x00000024
	KCR_DECODE_ERROR          = KCR_BASE + 0x00000025
	KCR_XMLPARSEERROR         = KCR_BASE + 0x00000026
	KCR_XMLADDIDERROR         = KCR_BASE + 0x00000027
	KCR_XMLINTERNALERROR      = KCR_BASE + 0x00000028
	KCR_XMLSETSIGNERROR       = KCR_BASE + 0x00000029
	KCR_OPENSSLERROR          = KCR_BASE + 0x0000002a
	KCR_ENGINE_INITERR        = KCR_BASE + 0x0000002b
	KCR_NOTOKENFOUND          = KCR_BASE + 0x0000002c
	KCR_OCSP_ADDCERTERR       = KCR_BASE + 0x0000002d
	KCR_OCSP_PARSEURLERR      = KCR_BASE + 0x0000002e
	KCR_OCSP_ADDHOSTERR       = KCR_BASE + 0x0000002f
	KCR_OCSP_REQERR           = KCR_BASE + 0x00000030
	KCR_OCSP_CONNECTIONERR    = KCR_BASE + 0x00000031
	KCR_VERIFY_NODATA         = KCR_BASE + 0x00000032
	KCR_IDATTR_NOTFOUND       = KCR_BASE + 0x00000033
	KCR_IDRANGE               = KCR_BASE + 0x00000034
	KCR_XMLKEYDUPERROR        = KCR_BASE + 0x00000035
	KCR_XMLKEYCREATEERROR     = KCR_BASE + 0x00000036
	KCR_READERNOTFOUND        = KCR_BASE + 0x00000037
	KCR_GETCERTPROPERR        = KCR_BASE + 0x00000038
	KCR_SIGNFORMMAT           = KCR_BASE + 0x00000039
	KCR_INDATAFORMAT          = KCR_BASE + 0x0000003a
	KCR_OUTDATAFORMAT         = KCR_BASE + 0x0000003b
	KCR_VERIFY_INIT_ERROR     = KCR_BASE + 0x0000003c
	KCR_VERIFY_ERROR          = KCR_BASE + 0x0000003d
	KCR_HASH_ERROR            = KCR_BASE + 0x0000003e
	KCR_SIGNHASH_ERROR        = KCR_BASE + 0x0000003f
	KCR_CACERTNOTFOUND        = KCR_BASE + 0x00000040
	KCR_CERTTIMEINVALID       = KCR_BASE + 0x00000042
	KCR_CONVERTERROR          = KCR_BASE + 0x00000043
	KCR_TSACREATEQUERY        = KCR_BASE + 0x00000044
	KCR_CREATEOBJ             = KCR_BASE + 0x00000045
	KCR_CREATENONCE           = KCR_BASE + 0x00000046
	KCR_HTTPERROR             = KCR_BASE + 0x00000047
	KCR_CADESBES_FAILED       = KCR_BASE + 0x00000048
	KCR_CADEST_FAILED         = KCR_BASE + 0x00000049
	KCR_NOTSATOKEN            = KCR_BASE + 0x0000004a
	KCR_INVALID_DIGEST_LEN    = KCR_BASE + 0x0000004b
	KCR_GENRANDERROR          = KCR_BASE + 0x0000004c
	KCR_SOAPNSERROR           = KCR_BASE + 0x0000004d
	KCR_GETPUBKEY             = KCR_BASE + 0x0000004e
	KCR_GETCERTINFO           = KCR_BASE + 0x0000004f
	KCR_FILEREADERROR         = KCR_BASE + 0x00000050
	KCR_CHECKERROR            = KCR_BASE + 0x00000051
	KCR_ZIPEXTRACTERR         = KCR_BASE + 0x00000052
	KCR_NOMANIFESTFILE        = KCR_BASE + 0x00000053
	KCR_LIBRARYNOTINITIALIZED = KCR_BASE + 0x00000101
	KCR_ENGINELOADERR         = KCR_BASE + 0x00000200
	KCR_PARAM_ERROR           = KCR_BASE + 0x00000300
	KCR_CERT_STATUS_OK        = KCR_BASE + 0x00000400
	KCR_CERT_STATUS_REVOKED   = KCR_BASE + 0x00000401
	KCR_CERT_STATUS_UNKNOWN   = KCR_BASE + 0x00000402
)

type KCReturnValue int

func (i KCReturnValue) GetError() string {
	var message string
	switch i {
	case KCR_OK:
		message = "KCR_OK"
	case KCR_INIT_ERROR:
		message = "KCR_INIT_ERROR"
	case KCR_ERROR_READ_PKCS12:
		message = "KCR_ERROR_READ_PKCS12"
	case KCR_ERROR_OPEN_PKCS12:
		message = "KCR_ERROR_OPEN_PKCS12"
	case KCR_INVALID_PROPID:
		message = "KCR_INVALID_PROPID"
	case KCR_BUFFER_TOO_SMALL:
		message = "KCR_BUFFER_TOO_SMALL"
	case KCR_CERT_PARSE_ERROR:
		message = "KCR_CERT_PARSE_ERROR"
	case KCR_INVALID_FLAG:
		message = "KCR_INVALID_FLAG"
	case KCR_OPENFILEERR:
		message = "KCR_OPENFILEERR"
	case KCR_INVALIDPASSWORD:
		message = "KCR_INVALIDPASSWORD"
	case KCR_CERTWRONGDATE:
		message = "KCR_CERTWRONGDATE"
	case KCR_CERTEXPIRED:
		message = "KCR_CERTEXPIRED"
	case KCR_ISNOTCACERT:
		message = "KCR_ISNOTCACERT"
	case KCR_MEMORY_ERROR:
		message = "KCR_MEMORY_ERROR"
	case KCR_CHECKCHAINERROR:
		message = "KCR_CHECKCHAINERROR"
	case KCR_CACERTKEYUSAGEERROR:
		message = "KCR_CACERTKEYUSAGEERROR"
	case KCR_VALIDTYPEERROR:
		message = "KCR_VALIDTYPEERROR"
	case KCR_BADCRLFORMAT:
		message = "KCR_BADCRLFORMAT"
	case KCR_LOADCRLERROR:
		message = "KCR_LOADCRLERROR"
	case KCR_LOADCRLSERROR:
		message = "KCR_LOADCRLSERROR"
	case KCR_UNKNOWN_ALG:
		message = "KCR_UNKNOWN_ALG"
	case KCR_KEYNOTFOUND:
		message = "KCR_KEYNOTFOUND"
	case KCR_SIGN_INIT_ERROR:
		message = "KCR_SIGN_INIT_ERROR"
	case KCR_SIGN_ERROR:
		message = "KCR_SIGN_ERROR"
	case KCR_ENCODE_ERROR:
		message = "KCR_ENCODE_ERROR"
	case KCR_INVALID_FLAGS:
		message = "KCR_INVALID_FLAGS"
	case KCR_CERTNOTFOUND:
		message = "KCR_CERTNOTFOUND"
	case KCR_VERIFYSIGNERROR:
		message = "KCR_VERIFYSIGNERROR"
	case KCR_BASE64_DECODE_ERROR:
		message = "KCR_BASE64_DECODE_ERROR"
	case KCR_UNKNOWN_CMS_FORMAT:
		message = "KCR_UNKNOWN_CMS_FORMAT"
	case KCR_GETHASHERROR:
		message = "KCR_GETHASHERROR"
	case KCR_CA_CERT_NOT_FOUND:
		message = "KCR_CA_CERT_NOT_FOUND"
	case KCR_XMLSECINIT_ERROR:
		message = "KCR_XMLSECINIT_ERROR"
	case KCR_LOADTRUSTEDCERTSERR:
		message = "KCR_LOADTRUSTEDCERTSERR"
	case KCR_SIGN_INVALID:
		message = "KCR_SIGN_INVALID"
	case KCR_NOSIGNFOUND:
		message = "KCR_NOSIGNFOUND"
	case KCR_DECODE_ERROR:
		message = "KCR_DECODE_ERROR"
	case KCR_XMLPARSEERROR:
		message = "KCR_XMLPARSEERROR"
	case KCR_XMLADDIDERROR:
		message = "KCR_XMLADDIDERROR"
	case KCR_XMLINTERNALERROR:
		message = "KCR_XMLINTERNALERROR"
	case KCR_XMLSETSIGNERROR:
		message = "KCR_XMLSETSIGNERROR"
	case KCR_OPENSSLERROR:
		message = "KCR_OPENSSLERROR"
	case KCR_ENGINE_INITERR:
		message = "KCR_ENGINE_INITERR"
	case KCR_NOTOKENFOUND:
		message = "KCR_NOTOKENFOUND"
	case KCR_OCSP_ADDCERTERR:
		message = "KCR_OCSP_ADDCERTERR"
	case KCR_OCSP_PARSEURLERR:
		message = "KCR_OCSP_PARSEURLERR"
	case KCR_OCSP_ADDHOSTERR:
		message = "KCR_OCSP_ADDHOSTERR"
	case KCR_OCSP_REQERR:
		message = "KCR_OCSP_REQERR"
	case KCR_OCSP_CONNECTIONERR:
		message = "KCR_OCSP_CONNECTIONERR"
	case KCR_VERIFY_NODATA:
		message = "KCR_VERIFY_NODATA"
	case KCR_IDATTR_NOTFOUND:
		message = "KCR_IDATTR_NOTFOUND"
	case KCR_IDRANGE:
		message = "KCR_IDRANGE"
	case KCR_XMLKEYDUPERROR:
		message = "KCR_XMLKEYDUPERROR"
	case KCR_XMLKEYCREATEERROR:
		message = "KCR_XMLKEYCREATEERROR"
	case KCR_READERNOTFOUND:
		message = "KCR_READERNOTFOUND"
	case KCR_GETCERTPROPERR:
		message = "KCR_GETCERTPROPERR"
	case KCR_SIGNFORMMAT:
		message = "KCR_SIGNFORMMAT"
	case KCR_INDATAFORMAT:
		message = "KCR_INDATAFORMAT"
	case KCR_OUTDATAFORMAT:
		message = "KCR_OUTDATAFORMAT"
	case KCR_VERIFY_INIT_ERROR:
		message = "KCR_VERIFY_INIT_ERROR"
	case KCR_VERIFY_ERROR:
		message = "KCR_VERIFY_ERROR"
	case KCR_HASH_ERROR:
		message = "KCR_HASH_ERROR"
	case KCR_SIGNHASH_ERROR:
		message = "KCR_SIGNHASH_ERROR"
	case KCR_CACERTNOTFOUND:
		message = "KCR_CACERTNOTFOUND"
	case KCR_CERTTIMEINVALID:
		message = "KCR_CERTTIMEINVALID"
	case KCR_CONVERTERROR:
		message = "KCR_CONVERTERROR"
	case KCR_TSACREATEQUERY:
		message = "KCR_TSACREATEQUERY"
	case KCR_CREATEOBJ:
		message = "KCR_CREATEOBJ"
	case KCR_CREATENONCE:
		message = "KCR_CREATENONCE"
	case KCR_HTTPERROR:
		message = "KCR_HTTPERROR"
	case KCR_CADESBES_FAILED:
		message = "KCR_CADESBES_FAILED"
	case KCR_CADEST_FAILED:
		message = "KCR_CADEST_FAILED"
	case KCR_NOTSATOKEN:
		message = "KCR_NOTSATOKEN"
	case KCR_INVALID_DIGEST_LEN:
		message = "KCR_INVALID_DIGEST_LEN"
	case KCR_GENRANDERROR:
		message = "KCR_GENRANDERROR"
	case KCR_SOAPNSERROR:
		message = "KCR_SOAPNSERROR"
	case KCR_GETPUBKEY:
		message = "KCR_GETPUBKEY"
	case KCR_GETCERTINFO:
		message = "KCR_GETCERTINFO"
	case KCR_FILEREADERROR:
		message = "KCR_FILEREADERROR"
	case KCR_CHECKERROR:
		message = "KCR_CHECKERROR"
	case KCR_ZIPEXTRACTERR:
		message = "KCR_ZIPEXTRACTERR"
	case KCR_NOMANIFESTFILE:
		message = "KCR_NOMANIFESTFILE"
	case KCR_LIBRARYNOTINITIALIZED:
		message = "KCR_LIBRARYNOTINITIALIZED"
	case KCR_ENGINELOADERR:
		message = "KCR_ENGINELOADERR"
	case KCR_PARAM_ERROR:
		message = "KCR_PARAM_ERROR"
	case KCR_CERT_STATUS_OK:
		message = "KCR_CERT_STATUS_OK"
	case KCR_CERT_STATUS_REVOKED:
		message = "KCR_CERT_STATUS_REVOKED"
	case KCR_CERT_STATUS_UNKNOWN:
		message = "KCR_CERT_STATUS_UNKNOWN"
	default:
		message = ""
	}
	return message
}
